# **NumPy**

In [2]:
import numpy as np
np.__version__

'1.22.4'

In [6]:
L1 = [12, 'fuad', 2.332]
for items in L1:
  print(type(items))
[type(item) for item in L1]

<class 'int'>
<class 'str'>
<class 'float'>


[int, str, float]

In [11]:
l2 = list(range(10))
print(l2)
l = []
for i in l2:
  l.append(str(i))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [22]:
# typecasting -- converting form form one data type to another
#numPy array will typecast any to match in the list since numpy array only takes one data type a time
import numpy as np
np.array([12,32,4,342,1,234,23], dtype=np.float32)  # intializing a 32 bit float precesion in the numpy array


array([ 12.,  32.,   4., 342.,   1., 234.,  23.], dtype=float32)

## **2D Arrays**
    - 2D arrays are 2 dimentional arrays they have rows and columns
    

In [29]:
np.zeros(10, dtype=np.int_) # away to create a numPy array of zeros



array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
#same as ones
np.ones((3, 6), dtype=np.float32)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [35]:
#random numpy array

np.random.random((3, 3))

array([[0.17269975, 0.30126526, 0.18583675],
       [0.471475  , 0.42433109, 0.42838457],
       [0.10895054, 0.339486  , 0.31667215]])

## **3D array**

In [43]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

## **slicing**
### **1D slicing**
- In 1D slicing, remember that **the start index is inclusive**, and the **stop index is exclusive**. The step size allows you to skip elements during the slicing process.
- always start count form 0

In [19]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
print(x[:5]) # the first 5 elements in the array
print(x[4:7]) # from 4th element to seventh
print(x[::2]) # every other element
print(x[1::2]) # every other from 1
print(x[-5:-1])

[0 1 2 3 4]
[4 5 6]
[0 2 4 6 8]
[1 3 5 7 9]
[5 6 7 8]


## **2D slicing**

In [17]:
import numpy as np

# Create a 2D array (3x3 matrix)
arr = np.array([[1, 2, 3,6],
                [4, 5, 6,8],
                [7, 8, 9,5]])

# Basic slicing to get the first two rows (rows 0 and 1) and the first two columns (columns 0 and 1)
subset1 = arr[:3, 2]
print(subset1)

[3 6 9]


### **Reshaping( )**
- Reshaping arrays in NumPy refers to changing the shape or dimensions of an existing array without modifying its data. NumPy provides the reshape() function to accomplish this task.

In [76]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr2 = arr1.reshape(2,5)
print(arr2)

arr3 = arr2.reshape(5,2)
arr3

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [42]:
import numpy as np # for 3d numpy where the input values (x, y, z) x is Dimention, y = is Row and Z = is column
x = np.array(([[1,2],
              [3,4]],
             [[5,6],
              [8,9]]), dtype=np.float32)
y = 5
x2 = np.add(x, 7)    # how np.add works
print(x2)

[[[ 8.  9.]
  [10. 11.]]

 [[12. 13.]
  [15. 16.]]]


## **UFunc (universal funtion)**
- this is a universal funtion it includes np.add, np.subtract, etc
  where the funtion takes 2 arguments e.g
  -
      import numpy as np
      x = np.array(([[1,2],
                  [3,4]],
                  [[5,6],
                  [8,9]]), dtype=np.float32)
      y = 5
      x2 = np.add(x, 7)
      print(x2)

## **Aggregate function**
- np.sum: Computes the sum of all elements in the array.
- np.mean: Computes the arithmetic mean (average) of the array elements.
- np.median: Computes the median (middle value) of the array elements.
- np.min: Finds the minimum value in the array.
- np.max: Finds the maximum value in the array.
- np.prod: Computes the product of all elements in the array.
- np.std: Computes the standard deviation of the array elements.
- np.var: Computes the variance of the array elements.
- np.any: Checks if any of the elements in the array evaluate to True.
- np.all: Checks if all elements in the array evaluate to True.
      - import numpy as np
      arr = np.array([1, 2, 3, 4, 5])

      # Sum of all elements
      sum_result = np.sum(arr)
      print(sum_result)  # Output: 15

      # Mean of all elements
      mean_result = np.mean(arr)
      print(mean_result)  # Output: 3.0

      # Median of all elements
      median_result = np.median(arr)
      print(median_result)  # Output: 3.0

      # Minimum value in the array
      min_result = np.min(arr)
      print(min_result)  # Output: 1

      # Maximum value in the array
      max_result = np.max(arr)
      print(max_result)  # Output: 5

      # Product of all elements
      prod_result = np.prod(arr)
      print(prod_result)  # Output: 120

      # Standard deviation of all elements
      std_result = np.std(arr)
      print(std_result)  # Output: 1.4142135623730951

      # Variance of all elements
      var_result = np.var(arr)
      print(var_result)  # Output: 2.0

      # Check if any element is greater than 3
      any_result = np.any(arr > 3)
      print(any_result)  # Output: True

      # Check if all elements are greater than 0
      all_result = np.all(arr > 0)
      print(all_result)  # Output: True
